local mon = peripheral.wrap("monitor_1")
local mon2 = peripheral.wrap("monitor_2")
local win = window.create(mon,1,1,7,5)
os.pullEvent("monitor_touch")
print("got it!")
mon.clear()
mon.setCursorPos(1,1)
win.write("hello")
win.redraw()
os.pullEvent("monitor_touch")

win.setParent(mon2)
win.write("bye")
win.redraw()

local co = coroutine.create(function() coroutine.yield() end)
local ok, msg,msg2 = coroutine.resume(co)
print(coroutine.status(co))
print(ok)
print(msg)
print(msg2)
